version: "3.9"
services:
  react-app-dev:
    build:
      context: . # tip: at the directory which contains THIS FILE, run cd <CONTEXT> will move to the root directory
      dockerfile: Dockerfile.dev # relative to context
    volumes:
      - ./:/react-app-dev # [host path]:[container path]
    ports:
      - "3000:3000" # [host port]:[container port]
  react-app-prod:
    build:
      context: . # tip: at the directory which contains THIS FILE, run cd <CONTEXT> will move to the root directory
      dockerfile: Dockerfile # relative to context
    volumes:
      - ./:/react-app # [host path]:[container path]
    ports:
      - "3333:80" # [host port]:[container port]
    command: ["nginx", "-g", "daemon off;"]
