services:
  react-app:
    container_name: "nginx-react-app"
    build:
      context: ../../../.. # tip: at the directory which contains THIS FILE, run cd <CONTEXT> will move to the root directory
      dockerfile: ./docker/webservers/nginx/Dockerfile # relative to context
    ports:
      - "3300:80" # [host post]:[container port]
    command: ["nginx", "-g", "daemon off;"]
