name: "Deploy to AWS"
on:
  push:
    tags:
      - "aws-**"
jobs:
  build-react-app:
    if: ${{ startsWith(github.ref_name, 'aws') }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          cache: yarn
      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
      - name: Build React app
        run: |
          yarn build:prod
      - uses: actions/upload-artifact@v3
        with:
          name: react-app-bundle
          path: ./dist

  deploy-to-aws-s3:
    if: ${{ startsWith(github.ref_name, 'aws-s3') }}
    needs:
      - build-react-app
    runs-on: ubuntu-22.04
    environment: production
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_S3_URI: ${{ secrets.AWS_S3_URI }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: react-app-bundle
          path: ./dist
      - name: Upload to S3
        run: |
          # aws cli is already available
          aws s3 sync ./dist "${AWS_S3_URI}" --delete --dryrun

  deploy-to-aws-lightsail:
    if: ${{ startsWith(github.ref_name, 'aws-lightsail') }}
    needs:
      - build-react-app
    runs-on: ubuntu-22.04
    environment: production
    env:
      LIGHTSAIL_INSTANCE_USERNAME: ${{ secrets.LIGHTSAIL_INSTANCE_USERNAME }}
      LIGHTSAIL_INSTANCE_PUBLIC_IP: ${{ secrets.LIGHTSAIL_INSTANCE_PUBLIC_IP }}
      LIGHTSAIL_INSTANCE_SSH_PRIVATE_KEY: ${{ secrets.LIGHTSAIL_INSTANCE_SSH_PRIVATE_KEY }}
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: react-app-bundle
          path: ./dist
      - name: Rsync to Lightsail instance
        run: |
          # rsync and ssh are already available
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          ssh-keyscan -H "$LIGHTSAIL_INSTANCE_PUBLIC_IP" >> ~/.ssh/known_hosts
          ssh-add <(echo "$LIGHTSAIL_INSTANCE_SSH_PRIVATE_KEY")
          rsync -avzP ./dist/ "$LIGHTSAIL_INSTANCE_USERNAME"@"$LIGHTSAIL_INSTANCE_PUBLIC_IP":/usr/share/nginx/html/react-app --delete

